In [47]:
import numpy as np
import pandas as pd


In [48]:
df = pd.read_csv('/content/heart.csv')

In [49]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [50]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [60]:
x = df.iloc[:,1:13].values


In [61]:
y = df['target'].values

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x = scaler.fit_transform(x)


In [63]:
y = np.asarray(y)

In [64]:
y.shape

(303,)

In [65]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_test,y_test = train_test_split(x,y,test_size=0.2)

In [35]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
#model = LogisticRegression()
model = XGBClassifier()
model.fit(x_train,x_test)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [36]:
y_pred = model.predict(y_train)

In [37]:
y_pred[0]

1

In [38]:
y_test[0]

1

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7377049180327869

In [66]:
from keras.models import Sequential
from keras.layers import Dense
clf = Sequential()

In [69]:
classifier = Sequential() 
classifier.add(Dense(activation = "relu", input_dim = 12,  
                     units = 8, kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "relu", units = 14,  
                     kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "sigmoid", units = 1,  
                     kernel_initializer = "uniform")) 
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy',  
                   metrics = ['accuracy'] )

In [70]:
classifier.fit(x_train,x_test,epochs=100,batch_size=8)

Epoch 1/100
242/242 [==============================] - 0s 1ms/step - loss: 0.6928 - accuracy: 0.6116
Epoch 2/100
242/242 [==============================] - 0s 160us/step - loss: 0.6879 - accuracy: 0.7645
Epoch 3/100
242/242 [==============================] - 0s 160us/step - loss: 0.6679 - accuracy: 0.8264
Epoch 4/100
242/242 [==============================] - 0s 161us/step - loss: 0.6153 - accuracy: 0.8512
Epoch 5/100
242/242 [==============================] - 0s 176us/step - loss: 0.5301 - accuracy: 0.8595
Epoch 6/100
242/242 [==============================] - 0s 160us/step - loss: 0.4425 - accuracy: 0.8554
Epoch 7/100
242/242 [==============================] - 0s 180us/step - loss: 0.3888 - accuracy: 0.8636
Epoch 8/100
242/242 [==============================] - 0s 176us/step - loss: 0.3629 - accuracy: 0.8595
Epoch 9/100
242/242 [==============================] - 0s 160us/step - loss: 0.3475 - accuracy: 0.8595
Epoch 10/100
242/242 [==============================] - 0s 152us/step - los

In [71]:
predictor = classifier.predict(y_train)

In [74]:
predictor[10]

array([0.9812441], dtype=float32)

In [75]:
y_test[10]

1

In [76]:
from keras.metrics import accuracy
accuracy(y_test,predictor)

<tf.Tensor: shape=(61, 61), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [78]:
classifier.evaluate(y_train,y_test)

61/61 [==============================] - 0s 376us/step


[0.4095600604033861, 0.8852459192276001]